
version: 0.2

run-as: Osagie devOps

phases:
  pre_build:
    commands:
      - echo Pre-build initializing...
      - npm install
  build:
    commands:
      - echo Build is being performed...
      - npm run build
  post-build:
    commands:
      - echo Testing for performance...
      - npm test
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build