
version: 0.2

phases:
  pre_build:
    commands:
      - echho Pre-build initializing ..
      - npm install
  build:
    commands:
      - echo Build is bring performed ;;;
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build